apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-demo
  ports:
    #port: 在集群内部，这个service在哪个port对外暴露
    #targetPort: 对应的pod expose在哪个端口，与deployment.yaml中container port相对应
    - port: 8080
      targetPort: 8080
      # 可选字段
      # 默认情况下，为了方便起见，Kubernetes 控制平面会从某个范围内分配一个端口号（默认：30000-32767）
      # Which port on the node is the service available through
      nodePort: 30940