apiVersion: v1
kind: Service
metadata:
  name: decision-service
spec:
  type: ClusterIP
  selector:
    app: decision-demo
  ports:
    # 默认情况下，为了方便起见，`targetPort` 被设置为与 `port` 字段相同的值。
    - port: 9898
      targetPort: 9898